project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating
    contents:
      - auto: "/*.ipynb"
      - section: Tutorials
        contents: tutorial/*
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Homepage"
        href: "https://nextrick.github.io/website/"
      - text: "Blog"
        menu:
          - text: "Graphic Design"
            href: blog/graphic_design/index.qmd
          - text: "AI"
            href: blog/graphic_design/index.qmd
    right:
      - icon: github
        href: "https://github.com/nextrick/Deep-Learning"

metadata-files: [nbdev.yml]