# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Practical-Programming',
                'doc_host': 'https://nextrick.github.io',
                'git_url': 'https://github.com/nextrick/Practical-Programming',
                'lib_path': 'Practical_Programming'},
  'syms': {'Practical_Programming.core': {'Practical_Programming.core.foo': ('core.html#foo', 'Practical_Programming/core.py')}}}
